server:
  port: 8002

dubbo:
  application:
    ##### 注册服务的名称
    name: user-web
  ##### 注册中心地址
  registry:
    address: zookeeper://39.106.90.140:2181
  ##### 调用服务超时时间
  consumer:
    timeout: 10000
