server:
  port: 8001

dubbo:
  application:
  ##### 注册服务的名称
    name: information-web
  ##### 注册中心地址
  registry:
    address: zookeeper://192.168.253.128:2181
  ##### 调用服务超时时间
  consumer:
    timeout: 10000